#spring:
# h2:
#    console:
#     enabled: true
#      path: /h2-console

# jpa:
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/utnspring
    username: flordaure
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop

